version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
  build:
    commands:
      - echo Build started on `date`
      - echo Building the application...
      # Copy index.html from SourceArtifact1 to the current build directory
      - cp /codebuild/output/src2/index.html .
  post_build:
    commands:
      - echo Build completed on `date`
      - mkdir -p output
      - cp index.html output/

artifacts:
  files:
    - '**/*'
