version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
  pre_build:
    commands:
      - echo Pre-build started on `date`
      - echo CODEBUILD_SRC_DIR $CODEBUILD_SRC_DIR
      - echo CODEBUILD_SRC_DIR_SourceArtifact2 $CODEBUILD_SRC_DIR_SourceArtifact2
  build:
    commands:
      - echo Build started on `date`
      - echo Building the application
      # Copy all files from SourceArtifact2 to the current build directory
      - cp -r $CODEBUILD_SRC_DIR_SourceArtifact2/* .
  post_build:
    commands:
      - echo Build completed on `date`
      - mkdir -p output
      # Copy only index.html on output directory 
      - cp index.html output/

artifacts:
  files:
    - '**/*'
